#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : abireport
Version  : 1.0.6
Release  : 10
URL      : https://github.com/clearlinux/abireport/releases/download/v1.0.6/abireport-1.0.6.tar.gz
Source0  : https://github.com/clearlinux/abireport/releases/download/v1.0.6/abireport-1.0.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: abireport-bin
Requires: abireport-license
Requires: abireport-man
BuildRequires : buildreq-golang

%description
abireport
----------
[![Report](https://goreportcard.com/badge/github.com/clearlinux/abireport)](https://goreportcard.com/report/github.com/clearlinux/abireport) [![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)

%package bin
Summary: bin components for the abireport package.
Group: Binaries
Requires: abireport-license
Requires: abireport-man

%description bin
bin components for the abireport package.


%package license
Summary: license components for the abireport package.
Group: Default

%description license
license components for the abireport package.


%package man
Summary: man components for the abireport package.
Group: Default

%description man
man components for the abireport package.


%prep
%setup -q -n abireport-1.0.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536630184
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1536630184
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/abireport
cp LICENSE %{buildroot}/usr/share/doc/abireport/LICENSE
cp src/vendor/github.com/spf13/cobra/LICENSE.txt %{buildroot}/usr/share/doc/abireport/src_vendor_github.com_spf13_cobra_LICENSE.txt
cp src/vendor/github.com/spf13/pflag/LICENSE %{buildroot}/usr/share/doc/abireport/src_vendor_github.com_spf13_pflag_LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/abireport

%files license
%defattr(-,root,root,-)
/usr/share/doc/abireport/LICENSE
/usr/share/doc/abireport/src_vendor_github.com_spf13_cobra_LICENSE.txt
/usr/share/doc/abireport/src_vendor_github.com_spf13_pflag_LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/abireport.1
